spring.application.name=search-apigateway
zuul.routes.search-apigateway.serviceId=search-service
zuul.routes.search-apigateway.path=/api/**

# Configuration for the eureka server
#eureka.client.registerWithEureka=true
#eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://192.168.60.48:8761/eureka/
# if app is dockerized
#eureka.client.serviceUrl.defaultZone=http://192.168.60.32:8761/eureka/