# if app is dockerized
spring.rabbitmq.host=172.17.0.2
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
originairports.shutdown=SEA

# Configuration for the eureka server
#eureka.client.registerWithEureka=true
#eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://192.168.60.48:8761/
# if app is dockerized
#eureka.client.serviceUrl.defaultZone=http://192.168.60.32:8761/eureka/